### ISSUE TITLE
DDR id should be "token" searchable

### ISSUE THREAD

**Issue by gjost** [densho/ddr-public#103]
From the webui standard search page, the user needs to search using the DDR id of collections, entities or files. 

The search webui needs to be able to parse the query for strings that look like DDR ids.

**Comment by GeoffFroh** [comment]
TODO: Need to define attributes that should be token searchable

**Comment by gjost** [comment]
Looks like we'll need to do some pre-processing of strings to identify and extract Densho-specific tokens before feeding them to Elasticsearch.

**Comment by GeoffFroh** [comment]
The title and description of this issue has been modified per the discussion 11/13

**Comment by gjost** [comment]
Fixed in develp branch as of commit 5eb8cdf.
