### ISSUE TITLE
Topic and Facility url values empty on segment detail pages

### ISSUE THREAD

**Issue by GeoffFroh** [densho/ddr-public#104]
On segment detail pages, Topic and Facility links in the right-hand metadata display area are not functional. The text terms are displayed; but the `href` values are empty. See:

https://ddrstage.densho.org/interviews/ddr-densho-1000-139-27/

The data is present in the raw `json` doc:

https://ddrstage.densho.org/api/0.2/ddr-densho-1000-139-27/

This behavior is not present in the regular entity detail template. Could be a problem in the segment specific templates only. See:

https://github.com/densho/ddr-public/blob/master/ddrpublic/ui/templates/ui/entities/segment-video.html#L375

**Comment by gjost** [comment]
Fixed in commit 1382ab8.
