### ISSUE TITLE
Remove hyperlinks for genre & format on entity detail page

### ISSUE THREAD

**Issue by sarabeckman** [densho/ddr-public#106]
The searches the hyperlinks for genre and format link to on the entity detail page are currently not working. See the links below. 
http://ddr.densho.org/search/results/?filter_genre=photograph
http://ddr.densho.org/search/results/?filter_format=img

The functionality is no longer of much value to the user so the links should be taken out of the templates for all entity detail pages.

**Comment by GeoffFroh** [comment]
Closed in commit 105f885

**Comment by gjost** [comment]
Also removed in hotfix commit 7382caa.
