### ISSUE TITLE
VH segment entities are not displayed with segment-video.html template

### ISSUE THREAD

**Issue by GeoffFroh** [densho/ddr-public#109]
Entities that are VH segment type are supposed to be displayed using the `segment-video.html` template (https://github.com/densho/ddr-public/blob/master/ddrpublic/ui/templates/ui/entities/segment-video.html). Currently, it appears that VH segment entities are being displayed using the old `segment.html` template instead. 

See, for example: 

https://ddrstage.densho.org/interviews/ddr-densho-1000-2-1/

Note that the `template` attribute in the raw ES json is set to `vh:video` as expected:

https://ddrstage.densho.org/api/0.2/ddr-densho-1000-2-1/

Switching logic for the templates lives in the entities view (https://github.com/densho/ddr-public/blob/master/ddrpublic/ui/views/entities.py#L17); and defaults to `segment.html`. It appears that somewhere, the `template` value is not being returned from ES and/or properly evaluated.

* Maybe an issue with `format_object_detail2` in `models.py` (https://github.com/densho/ddr-public/blob/3475435a9784d91f78805b0a7b0b5f64502f8f9f/ddrpublic/ui/models.py#L398)?

**Comment by gjost** [comment]
Turns out the template value resides in the *segment* not the entity.  Fixed in commit 2893d56.
