### ISSUE TITLE
webui: Remove child files list from special AV templates

### ISSUE THREAD

**Issue by GeoffFroh** [densho/ddr-public#111]
Child files list should not appear on AV templates. 

 ddrpublic/ui/templates/ui/entities/detail-audio.html
 ddrpublic/ui/templates/ui/entities/detail-video.html

**Comment by gjost** [comment]
Example audio: https://ddrstage.densho.org/ddr-csujad-28-1/

**Comment by gjost** [comment]
Any non-VH audio or video entity will only ever have media files and transcripts, and these are already in the UI.

**Comment by gjost** [comment]
Fixed in e0926cd
