### ISSUE TITLE
webui: Add extent info to description on audio-detail and video-detail templates

### ISSUE THREAD

**Issue by GeoffFroh** [densho/ddr-public#113]
The new audio and video detail templates:

ddrpublic/ui/templates/ui/entities/detail-audio.html
ddrpublic/ui/templates/ui/entities/detail-video.html

Should include `extent` info displayed under the Description section of the metadata sidebar, similar to the display in segment-audio and segment-video templates.

**Comment by gjost** [comment]
Example audio: https://ddrstage.densho.org/ddr-csujad-28-1/

**Comment by gjost** [comment]
Fixed in commit 81abe5b.
