### ISSUE TITLE
entities/video-detail.html binary download buttons are not correct

### ISSUE THREAD

**Issue by GeoffFroh** [densho/ddr-public#116]
The download buttons on the entity/video-detail.html template need modification. The only buttons should be the "Download transcript" and "Download MP4" buttons, similar to the segment-video.html template. See: https://github.com/densho/ddr-public/blob/master/ddrpublic/ui/templates/ui/entities/segment-video.html#L89

(Also need whitespace -- one `<p>` maybe -- between the top of the buttons and the video player itself.)

**Comment by gjost** [comment]
Fixed in commit db5201d.
