### ISSUE TITLE
ui: template switching logic in views/entities.py not functioning correctly for vh:audio entities

### ISSUE THREAD

**Issue by GeoffFroh** [densho/ddr-public#123]
Entities that are `vh:audio` are using the default `segment.html` instead of the proper`segment-audio.html` template.

**Comment by GeoffFroh** [comment]
Looks like it might be a view issue with entities.py (see: https://github.com/densho/ddr-public/blob/master/ddrpublic/ui/views/entities.py#L178). 

View source on an affected entity (e.g., view-source:https://ddrstage.densho.org/interviews/ddr-csujad-29-59-1/ line 267); `templatekey` is `None`

(However, that key is also missing for an entity that **works** -- see: view-source:https://ddrstage.densho.org/interviews/ddr-densho-1000-2-1/ line 269. The correct template is selected.)

**Comment by GeoffFroh** [comment]
Root cause is issue with `ddrindex` and data from IA. See: https://github.com/densho/ddr-cmdln/issues/155

**Comment by GeoffFroh** [comment]
There was also a related template issue. https://github.com/densho/ddr-public/issues/125

**Comment by gjost** [comment]
Fixed in ddr-cmdln commit d4d23ae for package ddrlocal-master_2.8.5.
