### ISSUE TITLE
ddr-densho-441 was published and (is) live despite being marked as `in-progress`

### ISSUE THREAD

**Issue by pkikawa** [densho/ddr-public#129]
ddr-densho-441 is marked as `in-progress` and `public` and live on the public site. this should not be live.
441 was created june 15 2018 with a last mod date of july 29 2019

to-do: 
reindex to ddrstage and see if it actually gets published
ddrindex delete from public site

**Comment by pkikawa** [comment]
Tested on Rainier && silverstar and ddrindex did publish objects marked as in-progress

**Comment by GeoffFroh** [comment]
Appears to be `ddrindex` issue -- opening in `ddr-cmdln` as: https://github.com/densho/ddr-cmdln/issues/165

**Comment by GeoffFroh** [comment]
`ddr-densho-1000-441` and its child entities have been manually removed from the production index.
