### ISSUE TITLE
Collection List Page broken links

### ISSUE THREAD

**Issue by sarabeckman** [densho/ddr-public#137]
All the links on the [collection list page](https://ddrstage.densho.org/collections/) to the different collections are not correct. All the links are just to the collection list page. 

The thumbnails for all collections and Partners are also missing from the collections list page.

**Comment by gjost** [comment]
I see these.  Working on it.

**Comment by gjost** [comment]
Restored the collection thumbnails and links.  Still need to work on the partner logos.

**Comment by gjost** [comment]
Partner logos are fixed.

This and the thumbnails thing happened because all these queries that previously used `docstore.search` and returned raw Elasticsearch objects are now using `search.Searcher` and returning the same `SearchResults` objects  that are used in the API.
