### ISSUE TITLE
String indices must be integers error with all Visual History materials

### ISSUE THREAD

**Issue by sarabeckman** [densho/ddr-public#138]
When trying to load any Visual History [object page](https://ddrstage.densho.org/ddr-densho-1010-1/) an error page comes up with 'String Indices must be integers'. This behavior happens for every Visual History object across all collections. 

[TypeError at _ddr-densho-1010-1.txt](https://github.com/densho/ddr-public/files/3848239/TypeError.at._ddr-densho-1010-1.txt)

**Comment by gjost** [comment]
Visual History pages have been fixed as of commit `262b2da33d`.
