### ISSUE TITLE
Mismatch between topics tree counts and list page counts

### ISSUE THREAD

**Issue by gjost** [densho/ddr-public#139]
Object counts in the Topics subtree on topics detail pages do not match the counts in the object list section.
```
Religion and churches (130)
    Buddhism (634)
...
631 items
```
Some affected pages:
https://ddrstage.densho.org/browse/topics/6/
https://ddrstage.densho.org/browse/topics/65/
https://ddrstage.densho.org/browse/topics/395/

**Comment by gjost** [comment]
Disparity betw list query and the query that generates topics tree counts

**Comment by gjost** [comment]
Right now it looks to me like this is some error in Elasticsearch itself(?)

This is the code that gets a list of objects for a particular term:
```
    def objects(facet_id, term_id, request=None, limit=DEFAULT_LIMIT, offset=0):
        ...
            params = {'match_all': 'true'}
            params[facet_id] = term_id
            searcher = search.Searcher()
            searcher.prepare(
                params=params,
                fields_nested=[],
                fields_agg={},
            )
            results = searcher.execute(limit, offset)
```
And this is the code that generates the topics tree count:
```
    def term_aggs_nested(terms, doctypes=[], fieldname=''):
        searcher = search.Searcher()
        searcher.prepare(params={'match_all': 'true'})
        results = searcher.execute(10000, 0)
        # fieldname:term:id dict
        aggs = {}
        for fieldname,data in results.aggregations.items():
            aggs[fieldname] = {}
            for item in data:
                aggs[fieldname][item['key']] = item['doc_count']
        # assign doc_count per term
        for term in terms:
            fid = term['facet']
            tid = str(term['term_id'])
            term['doc_count'] = 0
            if aggs.get(fid) and aggs[fid].get(tid):
                term['doc_count'] = aggs[fid].get(tid)
```
They're basically working with the same result set, except that the object-list function adds the term ID as a search term.  This code is the same:
```
        searcher = search.Searcher()
        searcher.prepare(params={'match_all': 'true'})
        results = searcher.execute(10000, 0)
```
The tree function works with aggregations but it doesn't do any calculations.  If you print out `aggs['topics']['1']` in the second function you will get the exact value that is listed in the tree.  As far as I can tell this comes directly from Elasticsearch.

**Comment by gjost** [comment]
If it's really crucial to have the exact same numbers, I guess we could just run the `Term.objects` function on each term.  It takes ~10s so we'd obviously want to cache it but it's not *too* bad.
```
>>> from datetime import datetime
>>> from django.conf import settings
>>> from ui import models
>>> start = datetime.now()
>>> terms = models.Facet.topics_terms(request=None)
>>> term_counts = {}
>>> for term in terms:
...     results = models.Term.objects('topics', str(term['term_id']), limit=settings.RESULTS_PER_PAGE, offset=0, request=None)
...     term_counts[term['id']] = {'doc_count': term['doc_count'], 'results.total': results.total, 'title': term['title']}
>>>
>>> term_counts
{'topics-406': {'doc_count': 0, 'results.total': 0, 'title': 'Funerals'}, 'topic...
>>> elapsed = datetime.now() - start
>>> elapsed
datetime.timedelta(0, 10, 260287)
```

**Comment by GeoffFroh** [comment]
Let's use the `Term.objects` function and aggressively cache. The counts should only change when we index new content which does not happen every day. So maybe once a day?

**Comment by gjost** [comment]
Sounds good. We can always log in and wipe the cache if we need it to
update sooner.

**Comment by gjost** [comment]
Fixed in `ddrpublic` commit `b61b609` (no package as yet) and deployed on stage for testing.

**Comment by gjost** [comment]
Looks like it's working for topics but very broken for facility.

**Comment by gjost** [comment]
Fixed counts on `browse/facility/` page in commit `bacc707`. Stupid typo.
