### ISSUE TITLE
VH segments not appearing in search results

### ISSUE THREAD

**Issue by GeoffFroh** [densho/ddr-public#142]
After the most recent master release, VH segments are no longer appearing in search results. VH interview entities are still present. 

Example: https://ddr.densho.org/search/?fulltext=minidoka+school&page=3&format=vh

**Comment by GeoffFroh** [comment]
Confirmed that there is data for individual segments in the `ddrsegment` index on the production cluster.

**Comment by gjost** [comment]
Fixed in ddr-public commit 33038d0 for package ddrpublic-master_4.0.2~deb9_amd64.deb (deployed).
