### ISSUE TITLE
500 error when searching for narrator http://ddr.densho.org/narrators/174/

### ISSUE THREAD

**Issue by pkikawa** [densho/ddr-public#143]
searching for "hayes" or "elaine ishikawa" or "ishikawa hayes" or "elaine hayse" throws 500 error

http://ddr.densho.org/search/results/?fulltext=hayes

**Comment by gjost** [comment]
Certain narrator fields expected by the formatter function were not included in `SEARCH_INCLUDE_FIELDS`, causing the error.

Fixed in ddr-public commit 8b88184 for package `ddrpublic-master_4.0.3~deb9`.
