### ISSUE TITLE
new Archive.org JWPlayer

### ISSUE THREAD

**Issue by gjost** [densho/ddr-public#66]
Archive.org has updated to a new version of JWPlayer: https://blog.archive.org/2018/04/11/audio-video-player-updated-to-jwplayer-v8-2/

**Comment by GeoffFroh** [comment]
Looks like the old player code has been removed. This must be addressed ASAP as OH clips are currently down. I'm working on a hotfix branch off develop.

**Comment by GeoffFroh** [comment]
Fixed in 7ae0844f23696f689eeaa1b6a35b9e6125738a4b
