### ISSUE TITLE
Cannot download full-size objects

### ISSUE THREAD

**Issue by CamJohns** [densho/ddr-public#73]

**Comment by gjost** [comment]
Better description:

Download links are not working on object detail pages.  On object pages, the "Download large" link works fine but "Download full-size" link just reloads the page.  On file pages, the "Download large size" link is fine.
https://ddrstage.densho.org/ddr-densho-289-1/
https://ddrstage.densho.org/ddr-densho-289-1-mezzanine-8c6ef04997/

**Comment by gjost** [comment]
Fixed in commit e314e1a plus a forthcoming `ddrindex` commit in `ddr-cmdln`.
