### ISSUE TITLE
Technical Details field is missing data on the item-level page

### ISSUE THREAD

**Issue by CamJohns** [densho/ddr-public#75]

**Comment by gjost** [comment]
Can you be more specific?  Please include URL of a specific page that exhibits the problem, and point out exactly what is supposed to be there which isn't.

**Comment by pkikawa** [comment]
https://ddrstage.densho.org/ddr-densho-200-5-mezzanine-15d0fb1c75/

technical details field (between size and rights) is empty

**Comment by gjost** [comment]
Fixed in `ddr-defs` commit 38b3a5f.
