### ISSUE TITLE
next/previous/first/last page buttons are non-functional 

### ISSUE THREAD

**Issue by pkikawa** [densho/ddr-public#76]
from a collection page the next/previous/first/last page buttons do not work (seems to just reload the objects already on the page [ https://ddrstage.densho.org/ddr-densho-266/])

Clarification: the collection objects page: https://ddrstage.densho.org/ddr-densho-266/objects/

**Comment by gjost** [comment]
Collection objects page first/prev/next/last buttons are clickable and the page reloads but it always displays the same set of results.

**Comment by gjost** [comment]
Fixed in commit bfd2463.
