### ISSUE TITLE
ui: Add "we use cookies" notice

### ISSUE THREAD

**Issue by GeoffFroh** [densho/ddr-public#79]
Need a "we use cookies" dismissible banner notice at the bottom of the site. Use bootstrap-compatible code inserted into base.html template

**Comment by gjost** [comment]
Note: ddrpublic uses Bootstrap v3.3.6 plus that theme.

**Comment by GeoffFroh** [comment]
Fixed in 61f543ea5a3c9a65e8e318c4bb541e90a5257ec0

**Comment by gjost** [comment]
Nice, I'll pull that in to the `ddrpublic-support` and `develop` branches and get it installed.  I'll do the same for the other sites.
