### ISSUE TITLE
'file'-type documents should not appear in search results

### ISSUE THREAD

**Issue by GeoffFroh** [densho/ddr-public#80]
'file' documents in the Elasticsearch index should not be returned as part of general search results; the results set should only include 'narrator', 'entity', 'segment' and 'collection' types. 

This was the behavior in the previous version of `ddr-public`.

**Comment by gjost** [comment]
Could you provide an example please?  I'm been searching and can't find any file objects.  I've found some segments tho.

**Comment by gjost** [comment]
I've removed files from the list of doctypes eligible for search but I'll have to search through the master branch code to figure out how we excluded the segments before.

**Comment by gjost** [comment]
Oops, found this quote form Slack, answers my question

> (And we had decided to include only `narrator`, `entity`, `segment` and `collection` documents in search results to keep them from getting cluttered.)

**Comment by gjost** [comment]
Fixed in commit e21ab58.
