### ISSUE TITLE
ui: filters on search displaying key rather than display term

### ISSUE THREAD

**Issue by GeoffFroh** [densho/ddr-public#82]
Filter form fields for 'format', 'genre' and 'usage' attributes are displaying the key value rather than the display value. See this (currently in production):

https://ddr.densho.org/search/results/?fulltext=manzanar

vs. this (properly displayed in stage):

https://ddrstage.densho.org/search/results/?fulltext=manzanar

**Comment by gjost** [comment]
The fix for this is actually in `ddr-cmdln`.   As of `ddrlocal-master` version 2.5.1 the `ddrindex vocabs` command will now push labels for the remaining fields to Elasticsearch.  `ddr-public` will pick these up and display them.
To update, use `ddrlocal-master` version 2.5.1:
```
$ ddrindex vocabs /PATH/TO/ddr-vocab/api/0.2/
```
