### ISSUE TITLE
webui: "Object Genre" and "Object Format" no longer appear on entity detail page

### ISSUE THREAD

**Issue by GeoffFroh** [densho/ddr-public#87]
The "Object Genre" and "Object Format" attributes no longer show up on entity detail pages. See, e.g.:

https://ddr.densho.org/ddr-densho-12-1/

The json available through the api does have values for both attributes:

https://ddr.densho.org/api/0.2/ddr-densho-12-1/

IMPORTANT NOTE: The page should show the values from the corresponding controlled vocab, *not* the raw data values in the ES json document.  (http://partner.densho.org/vocab/api/0.2/genre.json or http://partner.densho.org/vocab/api/0.2/format.json)

This behavior is happening on both the production and stage sites.

**Comment by gjost** [comment]
Note: `forms/forms-choices` (e.g. http://192.168.56.1:9200/ddrpublic-20180508b/forms/forms-choices) caches this data for forms choices in an ES document.

**Comment by gjost** [comment]
Fixed in commit e65fef0.  Fix pulled to production and restarted.
