### ISSUE TITLE
Reconsider Internet Archive file metadata retrieval

### ISSUE THREAD

**Issue by gjost** [densho/ddr-public#91]
In Feb 2017 we added code that gets file information for segments from Internet Archive (commit 8e2af51).  This function hits IA for each segment at segment view time.  This retrieval takes ~1.5s.  The data is cached but currently the timeout is set for only one hour.

Considering that we refactored ddrpublic to pre-render object data to Elasticsearch, I propose that we include this step as well and bake this data into the ES documents.  Doing so would improve performance of the ddrpublic app and would reduce our requests to Internet Archve.

A short-time fix would be to increase the cache time for data from IA in the ddrpublic app.

**Comment by GeoffFroh** [comment]
I think it would be a good idea to do this on the front end -- i.e., during the indexing process. FWIW, the only data we do not have in the original DDR json doc is the filesize of the streaming version of the binary that is displayed to the user on the download button in the UI. 

It would also be worthwhile in the near term to increase the caching timeout for the data in the current ddrpublic. Again, it pretty much never changes.

**Comment by gjost** [comment]
Implemented in commit 26687c0.  See also `ddr-cmdln` commit 302a6fe.
