### ISSUE TITLE
ui: (css) wrong color for page indicator in pagination component

### ISSUE THREAD

**Issue by GeoffFroh** [densho/ddr-public#94]
CSS class for pagination indicator (`.pagination>.active>span:focus, .pagination>.active>span:hover`) is base bootstrap blue:

```
    background-color: #337ab7;
    border-color: #337ab7;
```

Should be theme orange (#F07057)

See, eg., http://ddr.densho.org/ddr-densho-122/objects/

**Comment by gjost** [comment]
Fixed in commit 033ba0b.
