### ISSUE TITLE
ui: modify download links on entity audio and video templates

### ISSUE THREAD

**Issue by GeoffFroh** [densho/ddr-public#97]
Currently, audio and video templates for plain entities use the same logic as the img/doc entity template to render download links. See:

https://github.com/densho/ddr-public/blob/master/ddrpublic/ui/templates/ui/entities/detail-audio.html#L107
https://github.com/densho/ddr-public/blob/master/ddrpublic/ui/templates/ui/entities/detail-video.html#L56

However, this does not work with audio and video content since, by default, those binaries are stored externally at IA. 

The two templates need to be modified to display the download link to the file download url at IA. The url should be to the original file as ingested at IA, and not any of the derivatives.

For ui mockup, see:

https://github.com/GeoffFroh/drv-public-ui/blob/master/drv-entityDetail-audioplayer.html
https://github.com/GeoffFroh/drv-public-ui/blob/master/drv-entityDetail-videoplayer.html

(This issue related to https://github.com/densho/ddr-public/issues/98)

**Comment by gjost** [comment]
Fixed in ffd4cc9 and d5c0e41.
