### ISSUE TITLE
ui: add transcript download btn to audio and video entity detail templates

### ISSUE THREAD

**Issue by GeoffFroh** [densho/ddr-public#98]
Audio and video templates for plain entities should have a "Download transcript" button if the entity has a `transcript`-role item in its child files. In the case of multiple transcript items, the logic should use the `sort` attribute if present (in ascending order). 

- Link should be to the full-size file, not the access-file
- Button should display human-friendly filesize

(This issue related to https://github.com/densho/ddr-public/issues/97)

**Comment by gjost** [comment]
This is already working for videos.

**Comment by gjost** [comment]
The only audio object I know of (ddr-csujad-28-1) has no transcript files, only mezzanines and masters.  Is this an oversight, or is there some other way I should be identifying transcripts?

**Comment by gjost** [comment]
Fixed in 153a65e and c43cb8b.
